debug: false

server:
    port: 8080

spring:
    application:
        name: LiveData
    rabbitmq:
        host: puffin.rmq2.cloudamqp.com
        port: 5672
        username: htcdtztc
        password: Ale4fZqeWyB0a3LkTXirce8yylWbz1hI
        virtual-host: htcdtztc
        listener:
            simple:
                prefetch: 100

rabbit-mq:
    default:
        exchange: binance.trade.exchange
    consumer:
        queue: binance.live.queue

websocket:
    allowed-origins: "*"
